[versions]
java = "21"

androidGradle = "8.9.1" # https://developer.android.com/reference/tools/gradle-api
androidCompileSDK = "35"
androidMinimalSDK = "28"

kwire = "1.1.0"
rakii = "1.1.0.6-SNAPSHOT"
kotlin = "2.1.20"
kotlinxCoroutines = "1.10.1"
dokka = "2.0.0" # https://github.com/Kotlin/dokka/releases"
karmaConventions = "1.3.7"
gradleNexus = "2.0.0" # https://github.com/gradle-nexus/publish-plugin/releases
libffi = "3.4.8-5"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
rakii-runtime = { module = "dev.karmakrafts.rakii:rakii-runtime", version.ref = "rakii" }

[plugins]
android-library = { id = "com.android.library", version.ref = "androidGradle" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradleNexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "gradleNexus" }
karmaConventions = { id = "dev.karmakrafts.conventions.karma-conventions", version.ref = "karmaConventions" }
rakii = { id = "dev.karmakrafts.rakii.rakii-gradle-plugin", version.ref = "rakii" }